### ISSUE TITLE
Jade mixins with multiple blocks

### ISSUE THREAD

**Issue by DanOlivier** [pugjs/pug#1274]
### Alternate title:  Jade vs. Yaml

Hello, I'm trying to obtain a flexible i18n page structure using Jade.
Basically, suppose I have multiple (possibly redundant or subtly different) Jade pages, each corresponding to it's own language (en, fr, de) :

``` jade
  .row
    .col-md-12
      section.panel.panel-primary#history
        .panel-heading
          h2.panel-title= i18n.t('app.history')
        .panel-body
          table.table.align-right
            thead
              tr
                th.col-md-2= i18n.t('app.column1')
                th.col-md-8= i18n.t('app.column2')
            tbody
              - var history = yaml.load(String(fs.readFileSync('./History.yaml')))
              +History(history.entry1)
                p Added (language-specific) history entry information
              +History(history.entry2)
                p Added (optional) information
```

Is there some way to take a Jade template, and parse it into a JS var (thus mapping it into hashes, objects, and/or sequences/arrays)?
The reason is that I could then build a mixin like this (while maintaining a uniform Jade syntax):

``` jade
  mixin History(item)
    //- This block should be completely language-neutral
    tr
      td
        if item.rangeText
          p.time-duration= item.rangeText
        else
          p.time-duration= item.range[0], item.range[1]
        p Continue to print #{item.field}
        //- Extra fields here
        //- Put block that follows +History here
        block
        //- unconventional, because item.field2 happens to be a jade template that needs to be expanded. With multiple blocks, this would be automatic
        p!= jadeLib.render(we.field2)
```

The imported yaml file from above might resemble:

``` yaml
  entry1:
    rangeText: Some text
    href: http://www.website.com/
    shortName: Short
    longName: 'Long name, with extra text'
    location: 'event took place here'
    headline: Something else
    field2: |
      ul
        li This is jade text
        li it may not seem important, but syntax and highlighting are lost (unless you can get your editor to understand the context)
    field3: |
      p Notice the href field above? What if I wanted an 
      | a(href='www.link.com') in-line link, or an enumeration of links:
      ul
        li: a(href='www.link.com') link1
        li: a(href='www.link.com') link1
```

So the yaml has the advantage that the import into JS is predictable, despite my poor familiarity with it. I can also import (and merge) multiple yaml files, a scheme that might allow me to factor-out the language-neutral parts, and easily reconcile those parts that are not.

However, I would like to know if it's possible to import Jade in a similar way as Yaml, such that the imported data is then fed into (amended by, or annotated by) the mixin. If the Jade were rendered into XML, imported into JS, then fed to the mixin (in streamlined and refined fashion), that would work. Thus, the top-level Jade file composes the content, the second contains the data (consisting primarily of yet more Jade/HTML), and the third (the mixin) structures/translates from more/less raw data, and inserts it into the main document.

The information to be presented is not overwhelmingly structured, and consists mostly of marked-up text.

Any comments/ideas on the above scheme?
Is it clean, innovative, dangerous, redundant? to render/expand Jade strings from within a (current) Jade rendering?

Thanks
Dan
